import { Destination, Hotel, Activity, Restaurant } from "./types";

// Mock Switrus Holidays Partner Destinations
export const destinations: Destination[] = [
    {
        id: "kerala",
        name: "Kerala - God's Own Country",
        description: "Backwaters, tea gardens, and pristine beaches",
        image: "/destinations/kerala.jpg",
        popularMonths: ["October", "November", "December", "January", "February"],
        averageBudget: { min: 25000, max: 80000 },
    },
    {
        id: "goa",
        name: "Goa - Beach Paradise",
        description: "Sun, sand, nightlife, and Portuguese heritage",
        image: "/destinations/goa.jpg",
        popularMonths: ["November", "December", "January", "February"],
        averageBudget: { min: 20000, max: 60000 },
    },
    {
        id: "rajasthan",
        name: "Rajasthan - Land of Kings",
        description: "Forts, palaces, deserts, and royal heritage",
        image: "/destinations/rajasthan.jpg",
        popularMonths: ["October", "November", "December", "January", "February"],
        averageBudget: { min: 30000, max: 100000 },
    },
    {
        id: "kashmir",
        name: "Kashmir - Paradise on Earth",
        description: "Snow-capped mountains, valleys, and Dal Lake",
        image: "/destinations/kashmir.jpg",
        popularMonths: ["April", "May", "June", "September", "October"],
        averageBudget: { min: 35000, max: 90000 },
    },
    {
        id: "ladakh",
        name: "Ladakh - Land of High Passes",
        description: "Monasteries, high-altitude lakes, and adventure",
        image: "/destinations/ladakh.jpg",
        popularMonths: ["June", "July", "August", "September"],
        averageBudget: { min: 40000, max: 120000 },
    },
];

// Mock Switrus Partner Hotels
export const hotels: Hotel[] = [
    // Kerala Hotels
    {
        id: "h1",
        name: "Vivanta Cochin",
        destination: "kerala",
        pricePerNight: 8500,
        rating: 4.5,
        amenities: ["Pool", "Spa", "Restaurant", "Wi-Fi", "Parking"],
        type: "luxury",
        image: "/hotels/vivanta-cochin.jpg",
    },
    {
        id: "h2",
        name: "Spice Garden Resort Thekkady",
        destination: "kerala",
        pricePerNight: 5000,
        rating: 4.2,
        amenities: ["Restaurant", "Wi-Fi", "Garden", "Parking"],
        type: "mid-range",
        image: "/hotels/spice-garden.jpg",
    },
    {
        id: "h3",
        name: "Alleppey Houseboat",
        destination: "kerala",
        pricePerNight: 12000,
        rating: 4.7,
        amenities: ["Private Deck", "Chef", "AC", "Scenic Views"],
        type: "luxury",
        image: "/hotels/houseboat.jpg",
    },
    {
        id: "h4",
        name: "Budget Inn Kochi",
        destination: "kerala",
        pricePerNight: 3000,
        rating: 3.8,
        amenities: ["Wi-Fi", "Breakfast", "Parking"],
        type: "budget",
        image: "/hotels/budget-inn.jpg",
    },

    // Goa Hotels
    {
        id: "h5",
        name: "Taj Exotica Goa",
        destination: "goa",
        pricePerNight: 15000,
        rating: 4.8,
        amenities: ["Beach Access", "Pool", "Spa", "Multiple Restaurants", "Wi-Fi"],
        type: "luxury",
        image: "/hotels/taj-goa.jpg",
    },
    {
        id: "h6",
        name: "Baga Beach Resort",
        destination: "goa",
        pricePerNight: 4500,
        rating: 4.0,
        amenities: ["Pool", "Restaurant", "Beach Proximity", "Wi-Fi"],
        type: "mid-range",
        image: "/hotels/baga-resort.jpg",
    },
    {
        id: "h7",
        name: "Anjuna Budget Stay",
        destination: "goa",
        pricePerNight: 2500,
        rating: 3.5,
        amenities: ["Wi-Fi", "Breakfast", "Beach Access"],
        type: "budget",
        image: "/hotels/anjuna-budget.jpg",
    },

    // Rajasthan Hotels
    {
        id: "h8",
        name: "Rambagh Palace Jaipur",
        destination: "rajasthan",
        pricePerNight: 20000,
        rating: 4.9,
        amenities: ["Heritage Property", "Pool", "Spa", "Fine Dining", "Garden"],
        type: "luxury",
        image: "/hotels/rambagh.jpg",
    },
    {
        id: "h9",
        name: "Haveli Heritage Udaipur",
        destination: "rajasthan",
        pricePerNight: 6000,
        rating: 4.3,
        amenities: ["Lake View", "Restaurant", "Rooftop", "Wi-Fi"],
        type: "mid-range",
        image: "/hotels/haveli-udaipur.jpg",
    },
    {
        id: "h10",
        name: "Desert Camp Jaisalmer",
        destination: "rajasthan",
        pricePerNight: 3500,
        rating: 4.0,
        amenities: ["Cultural Show", "Camel Safari", "Meals", "Bonfire"],
        type: "budget",
        image: "/hotels/desert-camp.jpg",
    },

    // Kashmir Hotels
    {
        id: "h11",
        name: "The LaLiT Grand Palace Srinagar",
        destination: "kashmir",
        pricePerNight: 12000,
        rating: 4.6,
        amenities: ["Dal Lake View", "Spa", "Restaurant", "Garden", "Wi-Fi"],
        type: "luxury",
        image: "/hotels/lalit-srinagar.jpg",
    },
    {
        id: "h12",
        name: "Houseboat Dal Lake",
        destination: "kashmir",
        pricePerNight: 4000,
        rating: 4.4,
        amenities: ["Lake View", "Private Deck", "Meals", "Shikara Ride"],
        type: "mid-range",
        image: "/hotels/kashmir-houseboat.jpg",
    },
    {
        id: "h13",
        name: "Gulmarg Alpine Resort",
        destination: "kashmir",
        pricePerNight: 5500,
        rating: 4.2,
        amenities: ["Mountain View", "Restaurant", "Heating", "Wi-Fi"],
        type: "mid-range",
        image: "/hotels/gulmarg-resort.jpg",
    },

    // Ladakh Hotels
    {
        id: "h14",
        name: "The Grand Dragon Ladakh",
        destination: "ladakh",
        pricePerNight: 10000,
        rating: 4.5,
        amenities: ["Mountain View", "Restaurant", "Oxygen Support", "Wi-Fi", "Parking"],
        type: "luxury",
        image: "/hotels/grand-dragon.jpg",
    },
    {
        id: "h15",
        name: "Leh Boutique Hotel",
        destination: "ladakh",
        pricePerNight: 4500,
        rating: 4.1,
        amenities: ["Rooftop", "Restaurant", "Wi-Fi", "Parking"],
        type: "mid-range",
        image: "/hotels/leh-boutique.jpg",
    },
    {
        id: "h16",
        name: "Nubra Valley Camps",
        destination: "ladakh",
        pricePerNight: 3000,
        rating: 3.9,
        amenities: ["Valley View", "Meals", "Bonfire", "Adventure Activities"],
        type: "budget",
        image: "/hotels/nubra-camps.jpg",
    },
];

// Mock Switrus Partner Activities
export const activities: Activity[] = [
    // Kerala Activities
    {
        id: "a1",
        name: "Alleppey Backwater Cruise",
        destination: "kerala",
        price: 5000,
        duration: "8 hours",
        category: "nature",
        description: "Full day houseboat cruise through scenic backwaters",
        bestTimeOfDay: "morning",
    },
    {
        id: "a2",
        name: "Munnar Tea Plantation Tour",
        destination: "kerala",
        price: 2000,
        duration: "4 hours",
        category: "nature",
        description: "Guided tour of lush tea gardens with tasting session",
        bestTimeOfDay: "morning",
    },
    {
        id: "a3",
        name: "Kathakali Dance Show",
        destination: "kerala",
        price: 1500,
        duration: "2 hours",
        category: "culture",
        description: "Traditional Kerala classical dance performance",
        bestTimeOfDay: "evening",
    },
    {
        id: "a4",
        name: "Ayurvedic Spa Experience",
        destination: "kerala",
        price: 3500,
        duration: "3 hours",
        category: "relaxation",
        description: "Authentic Ayurvedic massage and wellness treatment",
        bestTimeOfDay: "afternoon",
    },
    {
        id: "a5",
        name: "Fort Kochi Heritage Walk",
        destination: "kerala",
        price: 800,
        duration: "3 hours",
        category: "culture",
        description: "Explore colonial architecture and Chinese fishing nets",
        bestTimeOfDay: "morning",
    },

    // Goa Activities
    {
        id: "a6",
        name: "Water Sports at Baga Beach",
        destination: "goa",
        price: 3000,
        duration: "2 hours",
        category: "adventure",
        description: "Parasailing, jet skiing, and banana boat rides",
        bestTimeOfDay: "morning",
    },
    {
        id: "a7",
        name: "Old Goa Churches Tour",
        destination: "goa",
        price: 1000,
        duration: "4 hours",
        category: "culture",
        description: "Visit UNESCO World Heritage churches and cathedrals",
        bestTimeOfDay: "morning",
    },
    {
        id: "a8",
        name: "Sunset Cruise on Mandovi River",
        destination: "goa",
        price: 1500,
        duration: "2 hours",
        category: "relaxation",
        description: "Romantic river cruise with live music and dinner",
        bestTimeOfDay: "evening",
    },
    {
        id: "a9",
        name: "Anjuna Flea Market Shopping",
        destination: "goa",
        price: 500,
        duration: "3 hours",
        category: "culture",
        description: "Shop for handicrafts, jewelry, and souvenirs",
        bestTimeOfDay: "afternoon",
    },
    {
        id: "a10",
        name: "Beach Party at Tito's",
        destination: "goa",
        price: 2000,
        duration: "4 hours",
        category: "nightlife",
        description: "Experience Goa's famous nightlife and beach clubs",
        bestTimeOfDay: "evening",
    },

    // Rajasthan Activities
    {
        id: "a11",
        name: "Amber Fort Sound & Light Show",
        destination: "rajasthan",
        price: 1200,
        duration: "1.5 hours",
        category: "culture",
        description: "Evening spectacular at historic Amber Fort",
        bestTimeOfDay: "evening",
    },
    {
        id: "a12",
        name: "Camel Safari in Thar Desert",
        destination: "rajasthan",
        price: 2500,
        duration: "3 hours",
        category: "adventure",
        description: "Experience desert life with camel ride and cultural program",
        bestTimeOfDay: "afternoon",
    },
    {
        id: "a13",
        name: "City Palace Jaipur Tour",
        destination: "rajasthan",
        price: 800,
        duration: "2 hours",
        category: "culture",
        description: "Explore the royal residence and museum",
        bestTimeOfDay: "morning",
    },
    {
        id: "a14",
        name: "Boat Ride on Lake Pichola",
        destination: "rajasthan",
        price: 1500,
        duration: "1 hour",
        category: "relaxation",
        description: "Scenic boat ride with views of Lake Palace",
        bestTimeOfDay: "evening",
    },
    {
        id: "a15",
        name: "Rajasthani Cultural Dinner",
        destination: "rajasthan",
        price: 2000,
        duration: "3 hours",
        category: "food",
        description: "Traditional Rajasthani thali with folk performances",
        bestTimeOfDay: "evening",
    },

    // Kashmir Activities
    {
        id: "a16",
        name: "Shikara Ride on Dal Lake",
        destination: "kashmir",
        price: 1000,
        duration: "1 hour",
        category: "relaxation",
        description: "Peaceful boat ride on the iconic Dal Lake",
        bestTimeOfDay: "morning",
    },
    {
        id: "a17",
        name: "Gulmarg Gondola Ride",
        destination: "kashmir",
        price: 3500,
        duration: "2 hours",
        category: "adventure",
        description: "World's highest cable car with stunning mountain views",
        bestTimeOfDay: "morning",
    },
    {
        id: "a18",
        name: "Mughal Gardens Tour",
        destination: "kashmir",
        price: 800,
        duration: "3 hours",
        category: "nature",
        description: "Visit Shalimar Bagh, Nishat Bagh, and Chashme Shahi",
        bestTimeOfDay: "afternoon",
    },
    {
        id: "a19",
        name: "Skiing at Gulmarg",
        destination: "kashmir",
        price: 5000,
        duration: "4 hours",
        category: "adventure",
        description: "Experience world-class skiing and snowboarding",
        bestTimeOfDay: "morning",
    },
    {
        id: "a20",
        name: "Kashmiri Wazwan Dinner",
        destination: "kashmir",
        price: 2500,
        duration: "2 hours",
        category: "food",
        description: "Traditional multi-course Kashmiri feast",
        bestTimeOfDay: "evening",
    },

    // Ladakh Activities
    {
        id: "a21",
        name: "Pangong Lake Excursion",
        destination: "ladakh",
        price: 6000,
        duration: "Full day",
        category: "nature",
        description: "Visit the stunning blue Pangong Tso lake",
        bestTimeOfDay: "morning",
    },
    {
        id: "a22",
        name: "Monastery Circuit Tour",
        destination: "ladakh",
        price: 2000,
        duration: "6 hours",
        category: "culture",
        description: "Visit Thiksey, Hemis, and Shey monasteries",
        bestTimeOfDay: "morning",
    },
    {
        id: "a23",
        name: "River Rafting on Zanskar",
        destination: "ladakh",
        price: 3500,
        duration: "4 hours",
        category: "adventure",
        description: "Thrilling white water rafting experience",
        bestTimeOfDay: "morning",
    },
    {
        id: "a24",
        name: "Nubra Valley Camel Safari",
        destination: "ladakh",
        price: 1500,
        duration: "2 hours",
        category: "adventure",
        description: "Ride Bactrian camels in the sand dunes",
        bestTimeOfDay: "afternoon",
    },
    {
        id: "a25",
        name: "Stargazing Experience",
        destination: "ladakh",
        price: 2000,
        duration: "3 hours",
        category: "nature",
        description: "Clear night sky viewing with expert guidance",
        bestTimeOfDay: "evening",
    },
];

// Mock Switrus Partner Restaurants
export const restaurants: Restaurant[] = [
    // Kerala Restaurants
    {
        id: "r1",
        name: "Malabar Cafe",
        destination: "kerala",
        cuisine: "Kerala Seafood",
        priceRange: "₹₹",
        specialty: "Karimeen Pollichathu",
        mealType: "lunch",
    },
    {
        id: "r2",
        name: "Dhe Puttu",
        destination: "kerala",
        cuisine: "Traditional Kerala",
        priceRange: "₹",
        specialty: "Variety Puttu",
        mealType: "breakfast",
    },
    {
        id: "r3",
        name: "Vivanta Multi-Cuisine",
        destination: "kerala",
        cuisine: "Multi-Cuisine",
        priceRange: "₹₹₹",
        specialty: "Continental & Indian",
        mealType: "dinner",
    },

    // Goa Restaurants
    {
        id: "r4",
        name: "Fisherman's Wharf",
        destination: "goa",
        cuisine: "Goan Seafood",
        priceRange: "₹₹₹",
        specialty: "Fish Recheado",
        mealType: "lunch",
    },
    {
        id: "r5",
        name: "Brittos",
        destination: "goa",
        cuisine: "Beach Shack",
        priceRange: "₹₹",
        specialty: "Prawns Balchao",
        mealType: "dinner",
    },
    {
        id: "r6",
        name: "Cafe Chocolatti",
        destination: "goa",
        cuisine: "Cafe",
        priceRange: "₹",
        specialty: "Breakfast Platter",
        mealType: "breakfast",
    },

    // Rajasthan Restaurants
    {
        id: "r7",
        name: "Chokhi Dhani",
        destination: "rajasthan",
        cuisine: "Rajasthani",
        priceRange: "₹₹₹",
        specialty: "Dal Baati Churma",
        mealType: "dinner",
    },
    {
        id: "r8",
        name: "LMB (Laxmi Mishthan Bhandar)",
        destination: "rajasthan",
        cuisine: "Vegetarian Rajasthani",
        priceRange: "₹₹",
        specialty: "Rajasthani Thali",
        mealType: "lunch",
    },
    {
        id: "r9",
        name: "Tapri Central",
        destination: "rajasthan",
        cuisine: "Cafe",
        priceRange: "₹",
        specialty: "Kulhad Tea & Snacks",
        mealType: "breakfast",
    },

    // Kashmir Restaurants
    {
        id: "r10",
        name: "Ahdoos Restaurant",
        destination: "kashmir",
        cuisine: "Kashmiri",
        priceRange: "₹₹₹",
        specialty: "Wazwan",
        mealType: "dinner",
    },
    {
        id: "r11",
        name: "Mughal Darbar",
        destination: "kashmir",
        cuisine: "Kashmiri",
        priceRange: "₹₹",
        specialty: "Rogan Josh",
        mealType: "lunch",
    },
    {
        id: "r12",
        name: "Chai Jaai",
        destination: "kashmir",
        cuisine: "Cafe",
        priceRange: "₹",
        specialty: "Kahwa & Pastries",
        mealType: "breakfast",
    },

    // Ladakh Restaurants
    {
        id: "r13",
        name: "Bon Appetit",
        destination: "ladakh",
        cuisine: "Multi-Cuisine",
        priceRange: "₹₹₹",
        specialty: "Rooftop Dining",
        mealType: "dinner",
    },
    {
        id: "r14",
        name: "Tibetan Kitchen",
        destination: "ladakh",
        cuisine: "Tibetan",
        priceRange: "₹₹",
        specialty: "Thukpa & Momos",
        mealType: "lunch",
    },
    {
        id: "r15",
        name: "Gesmo Restaurant",
        destination: "ladakh",
        cuisine: "Bakery & Cafe",
        priceRange: "₹",
        specialty: "Fresh Baked Goods",
        mealType: "breakfast",
    },
];

// Helper functions to filter data
export const getHotelsByDestination = (destinationId: string) =>
    hotels.filter((hotel) => hotel.destination === destinationId);

export const getActivitiesByDestination = (destinationId: string) =>
    activities.filter((activity) => activity.destination === destinationId);

export const getRestaurantsByDestination = (destinationId: string) =>
    restaurants.filter((restaurant) => restaurant.destination === destinationId);

export const getDestinationById = (id: string) =>
    destinations.find((dest) => dest.id === id);
